spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hanarodb?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: hanaro
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
      data-locations: classpath:data/data.sql
      encoding: UTF-8

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 512KB
      max-request-size: 3MB

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

app:
  upload:
    root: ${USER_HOME:/Users/jinlee}/Desktop/hanaro/uploads
  order:
    aging:
      toPreparingMinutes: 120
      toShippingMinutes: 720
      toDeliveredMinutes: 4320
logging:
  level:
    org.springdoc: debug
    org.springdoc.webmvc: TRACE